replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

auth:
    encoded: "YWRtaW46JGFwcjEkWVVCVjNkYWckRGx2QXZTSWlPOGxVZ2VDY0czLjZ6MQo="