apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;

        location / {
          root /usr/share/nginx/html;
          index index.html;
          auth_basic "Restricted Area";
          auth_basic_user_file /etc/nginx/.htpasswd;
        }

        error_page 404 /404.html;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-auth-config
data:
  .htpasswd: |
    {{ .Values.auth.encoded | b64dec }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-static-files
data:
  index.html: |
    <html>
    <head><title>Welcome</title></head>
    <body>
      <h1>Welcome to the NGINX App!</h1>
    </body>
    </html>
