apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;

        location / {
          root /usr/share/nginx/html;
          index index.html;
          auth_basic "Restricted Area";
          auth_basic_user_file /etc/nginx/.htpasswd;
        }

        error_page 404 /404.html;
      }
    }