apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    app: {{ .Release.Name }}-prometheus
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: {{ .Release.Name }}-prometheus